DROP TABLE IF EXISTS PERSONA;
DROP TABLE IF EXISTS PERSONA2;
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE PERSONA(ID INT PRIMARY KEY auto_increment, NOMBRE VARCHAR(20), APELLIDO VARCHAR(20));
CREATE TABLE USUARIO(ID INT PRIMARY KEY auto_increment, USUARIO VARCHAR(20), CONTRASENA VARCHAR(20), IDENTIFICACION VARCHAR(20), NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20), EMAIL VARCHAR(20));
CREATE TABLE PERSONA2(ID INT PRIMARY KEY auto_increment, COMODIN VARCHAR(20), PROCESO VARCHAR(20), FUENTE VARCHAR(20), USUARIO_ID INT(11), 
TERMINADO VARCHAR(1), ES_MUESTRA VARCHAR(1), ESTADO VARCHAR(1),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID));
INSERT INTO PERSONA (NOMBRE, APELLIDO) VALUES('JESUS', 'VILLALBA');